### PR TITLE
Fixes flash messages not being passed between requests

### LINKED ISSUE #6: Flash messages are not stored in the session
Flash messages are supposed to be stored in the session for later display (for example to display in the next page after a redirection).

This plugins seems to only keep the messages in the current request, which kind of defeats the purpose (you can just send your message directly in the data then). Here is an example that shows the bug. When you navigate to `/test`, then to `/test2`, the flash message is not properly passed, whereas the session data is kept correctly.

```const fastify = require("fastify")({ logger: true });
const fastifySession = require("fastify-secure-session");
const fastifyFlash = require("fastify-flash");

fastify.register(fastifySession, {
  // adapt this to point to the directory where secret-key is located
  key: "jdsqkfdjsklfjdslkfjdslkjfdsklflksdjfkljdsfkjlds",
  cookie: {
    // options from setCookie, see https://github.com/fastify/fastify-cookie
  }
});
fastify.register(fastifyFlash);

fastify.get("/test", (req, reply) => {
  req.flash("warning", ["username required", "password required"]);
  req.session.set("test", "testvalue");
  reply.send("test");
});
fastify.get("/test2", (req, reply) => {
  const warning = reply.flash("warning");
  const testValue = req.session.get("test");
  reply.send({ warning, testValue }); // {"warning":["username required","password required"]}
});

const start = async () => {
  try {
    await fastify.listen(3000);
    fastify.log.info(`server listening on ${fastify.server.address().port}`);
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};
start();
```

### PR DESCRIPTION
**Pull request by fox1t**
Fixes https://github.com/fastify/fastify-flash/issues/6

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — COMMENTED** [review]
Good work! Does this need a doc update.

**Comment by fox1t** [comment]
No, the exposed API is still the same. It is not a breaking change, so a patch might be ok.

**Comment by fox1t** [comment]
Do you want me to merge and release this, @mcollina ?

**Comment by mcollina** [comment]
That would be amazing, thanks!

Il giorno mar 10 mar 2020 alle ore 12:42 Maksim Sinik <
notifications@github.com> ha scritto:

**Pull request merged**
